data:
  my.cnf: |-
    [mysqld]

    skip_ssl

    default-time-zone = '+08:00'
    #设置大小写不敏感
    lower_case_table_names=1
    #设置字符集
    character-set-server=utf8
    collation-server=utf8_general_ci

    sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'

    max_connections = 1000

    skip-host-cache
    skip-name-resolve

    [mysql]
    #设置字符集
    default-character-set = utf8

    #sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'

    [mysql.server]
    #设置字符集
    default-character-set = utf8

    [mysqld_safe]
    #设置字符集
    default-character-set = utf8

    [client]
    #设置字符集
    default-character-set = utf8

    !includedir /etc/mysql/conf.d/
    !includedir /etc/mysql/mysql.conf.d/